{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "191c19ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "17867\n",
      "17867\n",
      "17867\n",
      "17867\n",
      "17867\n",
      "17866\n",
      "17868\n",
      "17868\n",
      "17866\n",
      "17868\n",
      "17867\n",
      "17868\n",
      "17867\n",
      "17867\n"
     ]
    }
   ],
   "source": [
    "#TODO: Make a user interface\n",
    "#TODO: Write file in chinese\n",
    "#TODO: Test\n",
    "\n",
    "DEBUG_MSG = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dd71b151",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<module 'shioaji_login' from 'C:\\\\Users\\\\pride829\\\\git\\\\shioaji-coverer\\\\shioaji_login.py'>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import json\n",
    "import time\n",
    "import datetime\n",
    "import traceback\n",
    "import threading\n",
    "import importlib\n",
    "import codecs\n",
    "\n",
    "from pathlib import Path\n",
    "\n",
    "import shioaji as sj\n",
    "import shioaji_login\n",
    "# Need to reload this for some reason that I can't remember.\n",
    "importlib.reload(shioaji_login)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "08d24ad5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def write_log(text):\n",
    "    \"\"\"\n",
    "    Write into log file.\n",
    "    \n",
    "    :param text: (str)\n",
    "    :return: None\n",
    "    \"\"\"\n",
    "\n",
    "    now = datetime.datetime.now()\n",
    "    path = 'coverer_logs'\n",
    "    try:\n",
    "        Path(path).mkdir(parents=True, exist_ok=True)\n",
    "    except FileExistsError:\n",
    "        # directory already exists\n",
    "        pass\n",
    "    \n",
    "    log_name = now.strftime('%Y%m%d') + '.log'\n",
    "    path = os.path.join(path, log_name)\n",
    "\n",
    "    # In order to let json dumps chinese correctly, codecs is needed.\n",
    "    # When ever use json dumps, specify ensure_ascii=False\n",
    "    fp = codecs.open(path, 'a+', 'utf16')\n",
    "    fp.write(text)\n",
    "    fp.close()\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "764903a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def stop_price_updater():\n",
    "    \"\"\"\n",
    "    Threading function.\n",
    "    Update stop price every single seconds.\n",
    "    If the time for now is inside of the range intense time, set the prices to intense version.\n",
    "    Otherwise, set them to normal version.\n",
    "    This thread will run as long as the program is running.\n",
    "    \n",
    "    :global param profit_stop: (int)\n",
    "    :global param loss_stop: (int)\n",
    "    :global param normal_profit_stop: (int)\n",
    "    :global param normal_loss_stop: (int)\n",
    "    :global param intense_profit_stop: (int)\n",
    "    :global param intense_loss_stop: (int)\n",
    "    \n",
    "    :return: None\n",
    "    \"\"\"\n",
    "    \n",
    "    global profit_stop, loss_stop\n",
    "    \n",
    "    pre_profit_stop = 0\n",
    "    pre_loss_stop = 0\n",
    "    \n",
    "    while(True):\n",
    "        now = datetime.datetime.now().time()\n",
    "        \n",
    "        if(now > intense_begin_time or now < intense_end_time):\n",
    "            profit_stop = intense_profit_stop\n",
    "            loss_stop = intense_loss_stop\n",
    "        else:\n",
    "            profit_stop = normal_profit_stop\n",
    "            loss_stop = normal_loss_stop\n",
    "        \n",
    "        if(pre_profit_stop != profit_stop or pre_loss_stop != loss_stop):\n",
    "            \n",
    "            print(f'Time is now {now.strftime(\"%H:%M:%S\")}')\n",
    "            print(f'Profit stop has been set to {profit_stop}')\n",
    "            print(f'Loss stop has been set to {loss_stop}')\n",
    "        \n",
    "        pre_profit_stop = profit_stop\n",
    "        pre_loss_stop = loss_stop\n",
    "        \n",
    "        time.sleep(1)\n",
    "        \n",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "482f9cec",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_future_code(future_name):\n",
    "    \"\"\"\n",
    "    Return future code based on future name\n",
    "    \n",
    "    :param future_name: (str)\n",
    "    \n",
    "    :return: future_code (str)\n",
    "    \"\"\"\n",
    "    \n",
    "    now = datetime.datetime.now().replace()\n",
    "    month = now.month\n",
    "    year = now.year\n",
    "    first_weekday = now.replace(day=1).weekday()\n",
    "    \n",
    "    # Calculate the dayt of the third wednesday\n",
    "    if(first_weekday < 3):\n",
    "        third_wednesday = 17 - first_weekday\n",
    "    else:\n",
    "        third_wednesday = 24 - first_weekday\n",
    "    \n",
    "    if(\n",
    "        now.day == third_wednesday and now.time() > datetime.time(13, 30) or\n",
    "        now.day > third_wednesday\n",
    "    ):\n",
    "        month = month + 1\n",
    "        if(month == 13):\n",
    "            month = 1\n",
    "            year += 1\n",
    "    \n",
    "    month_to_code = '0ABCDEFGHIJKL'\n",
    "    \n",
    "    future_code = future_name\n",
    "    future_code += month_to_code[month]\n",
    "    future_code += str(year%10)\n",
    "    \n",
    "    return future_code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3c83ae94",
   "metadata": {},
   "outputs": [],
   "source": [
    "def place_cover_order(quantity, action, original_price, market_price):\n",
    "    \"\"\"\n",
    "    Place the cover order.\n",
    "    \n",
    "    :global param: api (shioaji.shioaji.Shioaji)\n",
    "    :return: None\n",
    "    \"\"\"\n",
    "    fut_order = api.Order(\n",
    "        action=action,\n",
    "        price=0,\n",
    "        quantity=quantity,\n",
    "        price_type=sj.constant.FuturesPriceType.MKT,\n",
    "        order_type=sj.constant.FuturesOrderType.FOK, \n",
    "        octype=sj.constant.FuturesOCType.Cover,\n",
    "        account=api.futopt_account\n",
    "    )\n",
    "        \n",
    "    # Placing order\n",
    "    trade = api.place_order(contract, fut_order)\n",
    "    \n",
    "    print('***')\n",
    "    log_msg = f'An cover order with action={action}, quantity={quantity} has been placed!'\n",
    "    print(log_msg)\n",
    "    write_log(log_msg)\n",
    "    print(f'Trade msg: {trade.status.msg}')\n",
    "    write_log(f'Trade msg: {trade.status.msg}')\n",
    "    print('***\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "abe1cca1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "17858\n",
      "17859\n",
      "17857\n",
      "17859\n",
      "17857\n",
      "17857\n",
      "17857\n",
      "17857\n",
      "17857\n",
      "17857\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17857\n",
      "17856\n",
      "17856\n",
      "17857\n",
      "17856\n",
      "17857\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17855\n",
      "17856\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17857\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17855\n",
      "17855\n",
      "17857\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17854\n",
      "17855\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17855\n",
      "17854\n",
      "17854\n",
      "17853\n",
      "17853\n",
      "17852\n",
      "17852\n",
      "17853\n",
      "17852\n",
      "17854\n",
      "17852\n",
      "17852\n",
      "17852\n",
      "17852\n",
      "17853\n",
      "17853\n",
      "17852\n",
      "17852\n",
      "17854\n"
     ]
    }
   ],
   "source": [
    "def price_checker(market_price):\n",
    "    \"\"\"\n",
    "    Called every time market price is updated.\n",
    "    Update best price of every tracking positions based on market price.\n",
    "    Try to cover positions if stop price has been met.\n",
    "    :global param: positions (list)\n",
    "    :return: None\n",
    "    \"\"\"\n",
    "    \n",
    "    global positions\n",
    "    \n",
    "    for p in positions:\n",
    "        if(p[0] == 1):\n",
    "            p[3] = int(max(p[3], market_price))\n",
    "        elif(p[0] == -1 and market_price != 0):\n",
    "            p[3] = int(min(p[3], market_price))\n",
    "    \n",
    "    for p in positions:\n",
    "        \n",
    "        # Check if this positions is being cover\n",
    "        if(p[4]):\n",
    "            continue\n",
    "        \n",
    "        if(p[0] == 1):\n",
    "            cover_action = sj.constant.Action.Sell\n",
    "            if(market_price <= (p[2] - loss_stop)):\n",
    "                p[4] = True\n",
    "                print(f\"A loss stop has been detected. Market price: {market_price}, buy price: {p[2]}, best price: {p[3]}\")\n",
    "                place_cover_order(p[1], cover_action, p[2], market_price)\n",
    "                break\n",
    "            elif(market_price <= (p[3] - profit_stop)):\n",
    "                p[4] = True\n",
    "                print(f\"A profit stop has been detected. Market price: {market_price}, buy price: {p[2]}, best price: {p[3]}\")\n",
    "                place_cover_order(p[1], cover_action, p[2], market_price)\n",
    "                break\n",
    "        elif(p[0] == -1):\n",
    "            cover_action = sj.constant.Action.Buy\n",
    "            if(market_price >= (p[2] + loss_stop)):\n",
    "                p[4] = True\n",
    "                print(f\"A loss stop has been detected. Market price: {market_price}, sell price: {p[2]}, best price: {p[3]}\")\n",
    "                place_cover_order(p[1], cover_action, p[2], market_price)\n",
    "                break\n",
    "            elif(market_price >= (p[3] + profit_stop)):\n",
    "                p[4] = True\n",
    "                print(f\"A profit stop has been detected. Market price: {market_price}, sell price: {p[2]}, best price: {p[3]}\")\n",
    "                place_cover_order(p[1], cover_action, p[2], market_price)\n",
    "                break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "bb1173f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def fill_positions(deal):\n",
    "    \"\"\"\n",
    "    :global param positions: (list)\n",
    "    \n",
    "    :return: None\n",
    "    \"\"\"\n",
    "\n",
    "    global positions\n",
    "    # First check if the type and month match the tracking future.\n",
    "    if(\n",
    "        deal['code'] != contract['category'] or\n",
    "        deal['delivery_month'] != contract['delivery_month'] or\n",
    "        deal[\"security_type\"] != 'FUT'\n",
    "      ):\n",
    "        print(\"This deal is not as same as the future currently tracking.\")\n",
    "        return\n",
    "    \n",
    "    price = int(deal['price'])\n",
    "    quantity = int(deal['quantity'])\n",
    "    try:\n",
    "        if(deal['action'] == 'Buy'):\n",
    "            action = 1\n",
    "        elif(deal['action'] == 'Sell'):\n",
    "            action = -1\n",
    "        else:\n",
    "            raise ValueError('The action of this deal is neither \"Buy\" or \"Sell\".')\n",
    "    except ValueError as err:\n",
    "        traceback.print_exc()\n",
    "    \n",
    "    if(action == 1):\n",
    "        action_text = \"Long\"\n",
    "    else:\n",
    "        action_text = \"Short\"\n",
    "    \n",
    "    # While there are still some positions and it is the oppsite of the deal:\n",
    "    ori_quantity = quantity\n",
    "    while(positions and positions[0][0] == -action and quantity > 0):\n",
    "        \n",
    "        if(positions[0][1] > quantity):\n",
    "            positions[0][1] -= quantity\n",
    "            quantity = 0\n",
    "            # The deal has been recorded, exit the function\n",
    "            break\n",
    "        else:\n",
    "            quantity -= positions[0][1]\n",
    "            del positions[0]\n",
    "\n",
    "    print('***')\n",
    "    log_msg = f'A position with type={action_text}, quantity={ori_quantity}, price={price} has been recorded!'\n",
    "    print(log_msg)\n",
    "    write_log(log_msg)\n",
    "    print('***\\n')\n",
    "    \n",
    "    if (quantity > 0):\n",
    "        \n",
    "        # Ensure the data type is int\n",
    "        positions.append([action, int(quantity), int(price), int(price), False])\n",
    "        \n",
    "        if(action == 1):\n",
    "            positions = sorted(positions, key=lambda p: p[2], reverse=False)\n",
    "        else:\n",
    "            positions = sorted(positions, key=lambda p: p[2], reverse=True)\n",
    "\n",
    "        print('***')\n",
    "        log_msg = f'A position with type={action_text}, quantity={quantity}, price={price} has been added to the track list!'\n",
    "        print(log_msg)\n",
    "        write_log(log_msg)\n",
    "        print('***\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "6620c991",
   "metadata": {},
   "outputs": [],
   "source": [
    "msg_list = []\n",
    "\n",
    "def place_cb(stat, msg):\n",
    "    \"\"\"\n",
    "    Called every time an order or a deal has been detected.\n",
    "    \n",
    "    :global param: msg_list ()\n",
    "    \"\"\"\n",
    "    \n",
    "    global msg_list\n",
    "    \n",
    "    if(stat == sj.constant.OrderState.FOrder):\n",
    "        print('An order has been detected.')\n",
    "        print(f'op_msg: \\\"{msg[\"operation\"][\"op_msg\"]}\\\"')\n",
    "        write_log('stat: ' + stat + '\\nmsg: ' + json.dumps(msg, ensure_ascii=False) )\n",
    "        msg_list.append(msg)\n",
    "    elif(stat == sj.constant.OrderState.FDeal):\n",
    "        print('A deal has been detected.')\n",
    "        print(f'Deal information: code:{msg[\"code\"]}, action:{msg[\"action\"]}, price:{msg[\"price\"]}, quantity:{msg[\"quantity\"]}')\n",
    "        print(f'Delivery month:{msg[\"delivery_month\"]}, security type: {msg[\"security_type\"]}')\n",
    "        write_log('stat: ' + stat + '\\nmsg: ' + json.dumps(msg, ensure_ascii=False) )\n",
    "        msg_list.append(msg)\n",
    "        fill_positions(msg)\n",
    "        \n",
    "    # TODO: update_status may be useful?\n",
    "    #api.update_status(api.future_account)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "e4e77101",
   "metadata": {},
   "outputs": [],
   "source": [
    "def send_test_msg(\n",
    "    price,\n",
    "    quantity,\n",
    "    action,\n",
    "    stat=sj.constant.OrderState.FDeal,\n",
    "    code='MXF',\n",
    "    delivery_month='202201',\n",
    "    security_type='FUT'\n",
    "):\n",
    "    \"\"\"\n",
    "    For test purpose.\n",
    "    \"\"\"\n",
    "    # Testing with msg\n",
    "\n",
    "    msg = {}\n",
    "    msg['price'] = price\n",
    "    msg['quantity'] = quantity\n",
    "    msg['action'] = action\n",
    "    msg['code'] = code\n",
    "    msg['delivery_month'] = delivery_month\n",
    "    msg[\"security_type\"] = security_type\n",
    "\n",
    "    place_cb(stat, msg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a95818be",
   "metadata": {},
   "outputs": [],
   "source": [
    "def update_config():\n",
    "    \n",
    "    global intense_begin_time, intense_end_time, normal_profit_stop, normal_loss_stop, intense_profit_stop, intense_loss_stop\n",
    "    global future_name, future_code\n",
    "    \n",
    "    pre_future_code = None\n",
    "    while(True):\n",
    "        \n",
    "        with open('config.json') as f:\n",
    "            config_data = json.load(f)\n",
    "\n",
    "            intense_begin_time = datetime.datetime.strptime(config_data['intense_begin'], '%H:%M').time()\n",
    "            intense_end_time = datetime.datetime.strptime(config_data['intense_end'], '%H:%M').time()\n",
    "\n",
    "            normal_profit_stop = int(config_data['normal_profit_stop'])\n",
    "            normal_loss_stop = int(config_data['normal_loss_stop'])\n",
    "            intense_profit_stop = int(config_data['intense_profit_stop'])\n",
    "            intense_loss_stop = int(config_data['intense_loss_stop'])\n",
    "\n",
    "            future_name = config_data['future_name']\n",
    "        \n",
    "            # If auto_recent_future, get the most recent future code.\n",
    "            if(config_data['auto_recent_future'].lower() == 'true'):\n",
    "                future_code = get_future_code(future_name)\n",
    "            else:\n",
    "                future_code = config_data['future_code']\n",
    "        \n",
    "            if(pre_future_code != future_code):\n",
    "                print(f'Future code has been set to {future_code}')\n",
    "                pre_future_code = future_code\n",
    "        \n",
    "            time.sleep(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "edf18ef2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# This is a navie UI implementation. I wonder if there is some framework-like UI availible?\n",
    "\n",
    "def UI():\n",
    "    \"\"\"\n",
    "    Threading function.\n",
    "    User Interface.\n",
    "    \n",
    "    :global param: market_price (int)\n",
    "    \"\"\"\n",
    "    print(\"Waiting for commands...\")\n",
    "    while(True):\n",
    "        \n",
    "        try:\n",
    "            input_text = input()\n",
    "        except EOFError:\n",
    "            pass\n",
    "        \n",
    "        if(input_text == str('price')):\n",
    "            \n",
    "            print(f'Market price for {contract[\"code\"]}: {market_price}')\n",
    "            print(f'Profit stop: {profit_stop}, loss stop: {loss_stop}')\n",
    "            \n",
    "        elif(input_text == 'list'):\n",
    "            \n",
    "            print('The position currently tracking:')\n",
    "            \n",
    "            if not positions:\n",
    "                print('Empty.')\n",
    "                \n",
    "            for p in positions:\n",
    "                \n",
    "                if(p[0] == 1):\n",
    "                    action_text = \"Long\"\n",
    "                else:\n",
    "                    action_text = \"Short\"\n",
    "                \n",
    "                print(f'[Type: {action_text}, quantity: {p[1]}, deal price: {p[2]}, best price: {p[3]}]')\n",
    "           \n",
    "        \n",
    "        elif(input_text == 'contract'):\n",
    "            \n",
    "            print(f'Currently contract: {contract[\"code\"]}')\n",
    "            \n",
    "        elif(input_text == 'quit'):\n",
    "            \n",
    "            quit()\n",
    "            return\n",
    "        \n",
    "        elif(input_text == 'help'):\n",
    "            \n",
    "            print('price: Get the market price of currently contract. Also show the stop prices.')\n",
    "            print('list: List the position currently tracking.')\n",
    "            print('contract: Get the currently contract.')\n",
    "            print('quit: Exit the program.')\n",
    "            \n",
    "        else:\n",
    "            print(f'Command \"{input_text}\" is not recognized.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "039dde3c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Response Code: 0 | Event Code: 0 | Info: host '203.66.91.161:80', hostname '203.66.91.161:80' IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session up\n",
      "Login with ID N125685958\n",
      "Activating CA at the path C:\\Users\\pride829\\git\\shioaji-coverer\\sinopac\\Sinopac.pfx\n",
      "Future code has been set to MXFB2\n",
      "Time is now 16:46:23\n",
      "Profit stop has been set to 2\n",
      "Loss stop has been set to 2\n",
      "Response Code: 200 | Event Code: 16 | Info: TIC/v1/FOP/*/TFE/MXFB2 | Event: Subscribe or Unsubscribe ok\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-01-21 16:46:24.555 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:09.659000', '17896', '17899.3', 71288, 71265, '17892.54315', '17871', '17950', '17...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:24.558 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:09.739000', '17896', '17899.3', 71288, 71266, '17892.542932', '17871', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:24.561 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:09.856000', '17896', '17899.3', 71289, 71267, '17892.542714', '17871', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:24.563 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:09.887000', '17896', '17899.3', 71293, 71268, '17892.541841', '17871', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:24.566 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:10.516000', '17896', '17899.3', 71291, 71270, '17892.541613', '17870', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:24.832 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:11.110000', '17896', '17899.3', 71291, 71271, '17892.541384', '17870', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:26.084 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:12.314000', '17896', '17899.3', 71293, 71272, '17892.541156', '17870', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:26.459 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:12.639000', '17896', '17899.3', 71295, 71273, '17892.5407', '17870', '17950', '178...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-01-21 16:46:26.833 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:13.125000', '17896', '17899.3', 71295, 71274, '17892.540471', '17870', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:28.334 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:14.538000', '17896', '17899.3', 71296, 71275, '17892.540243', '17870', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:28.960 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.215000', '17896', '17899.3', 71296, 71277, '17892.540005', '17869', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.082 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.277000', '17896', '17899.3', 71297, 71280, '17892.53929', '17869', '17950', '17...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.084 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.278000', '17896', '17899.3', 71300, 71280, '17892.538813', '17869', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.210 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.431000', '17896', '17899.3', 71302, 71283, '17892.537819', '17868', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.216 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.463000', '17896', '17899.3', 71305, 71280, '17892.537581', '17869', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.458 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:15.692000', '17896', '17899.3', 71305, 71285, '17892.536587', '17868', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-01-21 16:46:29.833 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:16.084000', '17896', '17899.3', 71309, 71282, '17892.536349', '17869', '17950', '1...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n",
      "2022-01-21 16:46:29.836 | ERROR    | pysolace:msg_callback_wrap:99 - An error has been caught in function 'msg_callback_wrap', process 'MainProcess' (13172), thread 'Dummy-12' (6752):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"C:\\Users\\pride829\\anaconda3\\envs\\shioaji-coverer\\lib\\site-packages\\pysolace\\__init__.py\", line 99, in msg_callback_wrap\n",
      "    self.msg_callback(topic, msg)\n",
      "    │    │            │      └ {'content': ['MXFB2', '2022/01/22', '00:46:16.109000', '17896', '17899.3', 71310, 71283, '17892.53611', '17869', '17950', '17...\n",
      "    │    │            └ 'TIC/v1/FOP/idcdmzpcr01/TFE/MXFB2'\n",
      "    │    └ <bound method SolaceAPI.on_msg_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x000001B391F14948>>\n",
      "    └ <pysolace.SolClient object at 0x000001B3917AF108>\n",
      "\n",
      "> File \"shioaji\\backend\\solace\\api.pyx\", line 1677, in shioaji.backend.solace.api.SolaceAPI.on_msg_wrap\n",
      "  File \"shioaji\\backend\\solace\\api.pyx\", line 1720, in shioaji.backend.solace.api.SolaceAPI.on_quote_wrap\n",
      "\n",
      "  File \"C:\\Users\\pride829\\AppData\\Local\\Temp\\ipykernel_13172\\207249485.py\", line 51, in quote_callback\n",
      "    if(DEBUG_MSG):\n",
      "\n",
      "NameError: name 'DEBUG_MSG' is not defined\n"
     ]
    }
   ],
   "source": [
    "# Main\n",
    "\n",
    "api = shioaji_login.login()\n",
    "\n",
    "api.set_order_callback(place_cb)\n",
    "\n",
    "# Parsing config.json every second\n",
    "\n",
    "intense_begin_time = intense_end_time = normal_profit_stop = normal_loss_stop = intense_profit_stop = intense_loss_stop = None\n",
    "future_name = future_code = None\n",
    "\n",
    "update_config_thread = threading.Thread(target = update_config)\n",
    "update_config_thread.start()\n",
    "\n",
    "time.sleep(3)\n",
    "\n",
    "# profit_stop and loss_stop need to be initialize as None before calling stop_price_updater\n",
    "profit_stop = None\n",
    "loss_stop = None\n",
    "\n",
    "stop_price_updater_thread = threading.Thread(target = stop_price_updater)\n",
    "stop_price_updater_thread.start()\n",
    "\n",
    "# Get contract\n",
    "contract = api.Contracts.Futures[future_code]\n",
    "try:\n",
    "    if(not contract):\n",
    "        raise ValueError(f'Error: contract {future_code} does not exsits.')\n",
    "except ValueError as err:\n",
    "    traceback.print_exc()\n",
    "\n",
    "# positions is a list of list\n",
    "# Each single list cotains 5 values: Position_type, quantity, price, best_price, is_covering\n",
    "# Position_type determine the type of positions holding. 0: Neutral, 1: Long, -1: short\n",
    "positions = []\n",
    "\n",
    "# Update price with each tick and check.\n",
    "market_price = 0\n",
    "\n",
    "@api.on_tick_fop_v1()\n",
    "def quote_callback(exchange:sj.Exchange, tick:sj.TickFOPv1):\n",
    "    \"\"\"\n",
    "    Quoting subscribe function. It is called every tick(theoretically)\n",
    "    \n",
    "    :global param: market_price (int)\n",
    "    :return: None\n",
    "    \"\"\"\n",
    "    \n",
    "    global market_price\n",
    "    market_price = int(tick['close'])\n",
    "    if(DEBUG_MSG):\n",
    "        print(market_price)\n",
    "    price_checker(market_price)\n",
    "\n",
    "# Subscribe to the close price of the contract\n",
    "api.quote.subscribe(\n",
    "    contract,\n",
    "    quote_type = sj.constant.QuoteType.Tick, # or 'tick'\n",
    "    version = sj.constant.QuoteVersion.v1, # or 'v1'\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "36bbefc9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Start UI\n",
    "\n",
    "# Start UI with thread cause some EOF exceptions?\n",
    "#UI_thread = threading.Thread(target = UI)\n",
    "#UI_thread.start()\n",
    "\n",
    "# Simply run UI without threading.\n",
    "#UI()\n",
    "\n",
    "# This does not work quite well with Anaconda prompt\n",
    "#sys.exit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d8b698ff",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_13172\\506508464.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;36m1\u001b[0m\u001b[1;33m/\u001b[0m\u001b[1;36m0\u001b[0m \u001b[1;31m# Start Testing\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "1/0 # Start Testing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "4840e39d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A deal has been detected.\n",
      "Deal information: code:MXF, action:Buy, price:17850, quantity:2\n",
      "Delivery month:202202, security type: FUT\n",
      "***\n",
      "A position with type=Long, quantity=2, price=17850 has been recorded!\n",
      "***\n",
      "\n",
      "***\n",
      "A position with type=Long, quantity=2, price=17850 has been added to the track list!\n",
      "***\n",
      "\n",
      "17850\n",
      "17849\n",
      "17850\n",
      "17849\n",
      "17851\n",
      "17849\n",
      "A profit stop has been detected. Market price: 17849, buy price: 17850, best price: 17851\n",
      "***\n",
      "An cover order with action=Sell, quantity=2 has been placed!\n",
      "Trade msg: 憑證驗章失敗,請至3310憑證管理畫面憑證查詢狀態\n",
      "***\n",
      "\n",
      "17850\n",
      "17850\n",
      "17850\n",
      "17850\n",
      "17850\n",
      "17850\n",
      "17850\n",
      "17851\n",
      "17852\n",
      "17852\n",
      "17853\n",
      "17853\n",
      "17852\n",
      "17852\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17853\n",
      "17854\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17854\n",
      "17855\n",
      "17854\n",
      "17854\n",
      "17854\n",
      "17853\n",
      "17854\n",
      "17855\n",
      "17855\n",
      "17854\n",
      "17855\n",
      "17853\n",
      "17854\n",
      "17854\n",
      "17852\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17854\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17853\n",
      "17854\n",
      "17854\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17854\n",
      "17855\n",
      "17854\n",
      "17856\n",
      "17856\n",
      "17855\n",
      "17856\n",
      "17856\n",
      "17857\n",
      "17857\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17855\n",
      "17856\n",
      "17856\n",
      "17855\n",
      "17856\n",
      "17856\n",
      "17856\n",
      "17855\n"
     ]
    }
   ],
   "source": [
    "send_test_msg(\n",
    "    int(market_price),\n",
    "    2,\n",
    "    sj.constant.Action.Buy,\n",
    "    stat=sj.constant.OrderState.FDeal,\n",
    "    code='MXF',\n",
    "    delivery_month='202202',\n",
    "    security_type='FUT'\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "72404482",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "17864"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "market_price"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "69dcd021",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "17848\n",
      "17848\n",
      "17849\n",
      "17849\n",
      "17848\n",
      "17849\n",
      "17848\n",
      "17848\n",
      "17848\n",
      "17847\n",
      "17847\n",
      "17847\n",
      "17847\n",
      "17849\n",
      "17848\n",
      "17848\n",
      "17848\n",
      "17849\n",
      "17849\n",
      "17848\n",
      "17848\n",
      "17848\n",
      "17848\n",
      "17848\n",
      "17847\n",
      "17847\n",
      "17847\n",
      "17847\n",
      "17847\n",
      "17849\n",
      "17849\n",
      "17850\n"
     ]
    }
   ],
   "source": [
    "positions = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d45d7ad1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
